apiVersion: v1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 12.0.1
  name: grafana-config
  namespace: monitoring
stringData:
  grafana.ini: |
    [date_formats]
    default_timezone = UTC+1

    [server]
    protocol = https
    http_addr = 127.0.0.1
    http_port = 3000
    domain = "grafana.kube.infrafoundry.com"

    root_url = %(protocol)s://%(domain)s:%(http_port)s/

    # [auth]
    # signout_redirect_url = https://authentik.company/application/o/<application_slug>/end-session/
    # # Optionally enable auto-login
    # oauth_auto_login = true

    # [auth.generic_oauth]
    # name = authentik
    # enabled = true
    # client_id = j2yVxQOPQ30eqlPRxux9XuruTdvIqzqOHJclh8NV
    # client_secret = Ntnekgbz7RS6Fe4PxT3mxx74CEbtueJpPhxk05O4SveIVc5cURDncP8ySJq14kFGGz6IkvJ46VgF94J3f7fLyNU1yvyxqEmiceaBcL7VtYcfTxZbcOJvSpusbJfXWR1V
    # scopes = openid email profile
    # auth_url = https://authentik.company/application/o/authorize/
    # token_url = https://authentik.company/application/o/token/
    # api_url = https://authentik.company/application/o/userinfo/
    # # Optionally map user groups to Grafana roles
    # role_attribute_path = contains(groups, 'Grafana Admins') && 'Admin' || contains(groups, 'Grafana Editors') && 'Editor' || 'Viewer'
type: Opaque
